# Generated by Django 2.2.12 on 2020-05-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facemask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_image', models.ImageField(upload_to='facemask/full_image/')),
                ('thumbnail', models.ImageField(upload_to='facemask/thumbnail/')),
            ],
        ),
    ]
