# Generated by Django 2.2.12 on 2020-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20200511_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='facemask',
            name='mask_image',
            field=models.ImageField(blank=True, null=True, upload_to='facemask/mask_image/'),
        ),
    ]
