# Generated by Django 2.2.12 on 2020-06-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_facemask_mask_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facemask',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='facemask/original_image/'),
        ),
    ]
