# Generated by Django 2.2.12 on 2020-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='print_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
